name: lax-ogra
base: core18
adopt-info: lax
summary: electron based IRC client
description: |
  IRC client built with Electron & React

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  lax-ogra:
    extensions: [gnome-3-34]
    command: desktop-launch $SNAP/Lax --no-sandbox
    plugs:
      - audio-playback
      - browser-support
      - desktop
      - gsettings
      - network
      - network-bind
      - opengl
      - unity7
      - wayland
      - x11

parts:
  lax:
    source: https://github.com/brandly/Lax.git
    source-tag: v0.6.5
    plugin: nodejs
    nodejs-version: 12.18.2
    nodejs-package-manager: npm
    build-packages:
      - unzip
    stage-packages:
      - libnspr4
      - libnss3
      - libxss1
    override-build: |
      case $SNAPCRAFT_ARCH_TRIPLET in
        "i386-linux-gnu") ARCH="ia32";;
        "x86_64-linux-gnu") ARCH="x64";;
        "arm-linux-gnueabihf") ARCH="armv7l";;
        "aarch64-linux-gnu") ARCH="arm64";;
        *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
      esac
      PATH=$PATH:$SNAPCRAFT_PART_SRC/../npm/bin
      npm config set unsafe-perm True

      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      # skip use of OSX ditto to create zip (also, the command hardcodes darwin)
      sed -i 's/ditto/#ditto/' bin/build

      # app.dock does not exist on linux, dock icon is managed by .desktop file
      sed -i 's/app.dock.setIcon/\/\/app.dock.setIcon/' index.js

      # install build tools and build app
      npm install --save-dev @babel/core @babel/cli
      npm run build

      # set version
      VER="$(grep version package.json |sed 's/^.*: //;s/"//g;s/,//')"
      snapcraftctl set-version $VER

      # install to snap target
      cp -av ./dist/Lax-linux-$ARCH/* $SNAPCRAFT_PART_INSTALL/
  cleanup:
    after: [ lax ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      set -eux
      cd /snap/gnome-3-28-1804/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
